name: Node.js CI/CD Pipelines

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests 
        run: npm test

      # - name: Upload test results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: test-results
      #     path: test-results.xml
  build-docker:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t naul2354/todo-app-image:$(date '+%Y%m%d%H%M%S') .
    public-docker:
    needs: build-docker
    runs-on: ubuntu-latest

    steps:
      - name: Log into DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u naul2354 --password-stdin

      - name: Push Docker image
        run: docker push naul2354/todo-app-image:$(date '+%Y%m%d%H%M%S')
      

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to production (example)
  #       run: |
  #         # Add your deployment script here
  #         # For example, you can deploy to a server or a cloud platform
  #         echo "Deploying to production..."
